sample_folder: /home/data/Data_nano_ribolyzer/20230920_NucExp_IVPA_9bc_Cytoplasm1/pod5_original
color: Cytoplasm
script_folder: /home/data/nano_ribolyzer
output_folder: /home/data/Data_nano_ribolyzer/20230920_NucExp_IVPA_9bc_Cytoplasm1
basecalling_model: /home/dna_r10.4.1_e8.2_400bps_hac@v4.2.0
threads: 15
sample_type: DNA
